version: '3.5'

services:
  k8s:
    build: .
    volumes:
      - ./.kube:/home/app/.kube
      - ./.aws:/home/app/.aws
      - ./.ssh:/home/app/.ssh
      - ./.bash_history:/home/app/.bash_history
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
